import express from "express";
import { createRequestHandler } from "@react-router/express";
import path from "path";
import { fileURLToPath } from "url";
import { createServer } from "http";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const app = express();

// Serve static assets from the React Router client build
app.use(express.static(path.join(__dirname, "build/client"), {
  maxAge: "1h",
  immutable: true
}));

export async function startServer(port = 0) {
  // Dynamically import the SSR build generated by React Router v7
  const build = await import("./build/server/index.js");
  
  app.all("*", createRequestHandler({ build }));

  const server = createServer(app);
  return new Promise((resolve, reject) => {
    server.on('error', reject);
    server.listen(port, () => {
      resolve(server.address().port);
    });
  });
}

// Auto-start if run directly via Node/Bun
const isMain = import.meta.url === `file://${process.argv[1]}`;
if (isMain) {
  const port = process.env.PORT || 3001;
  startServer(port).then(actualPort => {
    console.log(`🚀 CAE Docs Server started on http://localhost:${actualPort}`);
  });
}